services:
  - type: web
    name: lawrei-beauty-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        sync: false
    healthCheckPath: /health
    autoDeploy: true
